version: '3.8'

services:
  server:
    image: 203918845423.dkr.ecr.ap-south-1.amazonaws.com/finalproject/server:latest
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app_network

  frontend:
    image: 203918845423.dkr.ecr.ap-south-1.amazonaws.com/finalproject/frontend:latest
    container_name: react_frontend
    restart: always
    ports:
      - "5001:5000"
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
