version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react_frontend
    restart: always
    ports:
      - "5001:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
